### PR TITLE
listing branches along with releases in list-all & release list fix

### PR DESCRIPTION
**Pull request by rrevanth**
fixed showing releases to show all the releases.currently it is not showing all the releases

### CODE REVIEW

**Comment by rrevanth** [comment]
I differentiated release and branches in separate echoe's . May be that's what causing the issue? Can you please test it and report so I can fix it!
Thanks!

**Comment by HashNuke** [comment]
@rrevanth list-all will/must always show only releases. It is upto the user to find and use a branch/commit to use. We assume that git installations are only for power-users.

Thank you for the time & effort. Closing this PR.
\cc: @tuvistavie

**Comment by HashNuke** [comment]
@rrevanth if you intended to fix the releases listing only, then please remove the branch listing and we'll test it out and reopen it.

**Comment by rrevanth** [comment]
Sure..I will do it right away!

**Pull request closed without merging**
