### PR TITLE
Show elixir version on test

### PR DESCRIPTION
**Pull request by robsonpeixoto**

### CODE REVIEW

**Comment by danhper** [comment]
Hi, thanks for the PR.
This will not work because the travis config is not using erlang.
If you could get it to pass the tests on Travis I would be more than happy to merge. I think it should be a matter of setting the language to `erlang` but I have not tried it.
https://docs.travis-ci.com/user/languages/erlang/

**Comment by Stratus3D** [comment]
I think you also may need to specify the OTP release you want to build with. See https://docs.travis-ci.com/user/languages/erlang/#choosing-otp-releases-to-test-against

**Comment by robsonpeixoto** [comment]
It is not working on macos: https://travis-ci.org/asdf-vm/asdf-elixir/builds/608131278
I'll close this PR, ok?

**Comment by Stratus3D** [comment]
@robsonpeixoto that's disappointing. I do think we need builds that work on OSX, so I'll close this. Thanks for giving this a try though. I really appreciate you taking the time to try to get this working.

**Pull request closed without merging**
