### PR TITLE
Add template to mktemp call so it will work on OSX

### PR DESCRIPTION
**Pull request by Stratus3D**

### CODE REVIEW

**Comment by HashNuke** [comment]
@Stratus3D Reverted this PR after merging. Was creating temp dirs in the current directory on Ubuntu.
Looks like it needs to be passed the full path of the temp dir.

**Comment by Stratus3D** [comment]
Your right, it should be `mktemp -d -t elixir_build_XXXXXX` on Ubuntu. I'll do more testing on OSX and Ubuntu and then update the PR.

**Comment by HashNuke** [comment]
@Stratus3D 👍
Can confirm that the `-t` option works with both ubuntu and OSX.

This PR was merged. So you'll probably have to create a new PR when you send one.

**Comment by Stratus3D** [comment]
Ok I opened PR #15, which includes the `-t` flag.

**Pull request merged**
