### PR TITLE
Fix 404 download error messages

### PR DESCRIPTION
**Pull request by duijf**
This PR improves upon the work @fkumro did in #2. Instead of downloading the entire file, we simply check the headers (I passed the `-I` option to `curl`).

Additionally, I've improved the error messages to make them correct.

Another issue related to this problem is #18, which we would be able to close when this get's merged.

### CODE REVIEW

**Comment by duijf** [comment]
I can't figure out what is happening on OS X (don't have a Mac). Could somebody take a look at what is happening with the list all command?

**Comment by HashNuke** [comment]
@duijf I'll look into it in a few hours.

**Comment by RobinClowers** [comment]
I just pulled this down and ran the plugin-test on my machine (macOS 10.11) and it appeared to pass. Maybe that test failure was a fluke?

**Comment by vic** [comment]
@RobinClowers  yeah, CI is failing for all builds, only for macos and it seems the list-all script is returning no versions. Will try to fix that this weekend and if also possible merge this.

**Comment by RobinClowers** [comment]
Anyone have a chance to look at this? The tests pass for me locally after rebasing master.

**Comment by duijf** [comment]
> Anyone have a chance to look at this? The tests pass for me locally after rebasing master.

I lost interest in this one, but found I still had this somewhere. I rebased on master and force pushed. Let's see what CI says

**Comment by duijf** [comment]
CI fails on both Linux and Mac, but I have the feeling that this is more due to rate limiting from GitHub when running on Travis (secrets are per repo and I don't have a GH token configured on my fork) than it is due to the code.

**Comment by Stratus3D** [comment]
It appears these changes work with anything prior to Elixir version `1.8.0-rc.1`. Since neither this PR branch nor master is able to install `1.8.0-rc.1` I'm guessing there may be an issue with this new version or there is something that has changed with the way Elixir versions are packaged. So I am going to merge this.

**Pull request merged**
